services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel-app
        container_name: laravel-app
        volumes:
            - .:/var/www
        command: ["supervisord", "-n"]
        networks:
            - app-network
        depends_on:
            - db # Ensure the database service is started before the app
        cpus: "2.0" # Limit to 2 CPUs
        mem_limit: 2G

    db:
        image: mysql:latest
        # healthcheck:
        #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        #     interval: 30s
        #     timeout: 10s
        #     retries: 5
        platform: linux/amd64
        container_name: mysql-db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
        ports:
            - "3307:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app-network
        cpus: "2.0" # Limit to 2 CPUs
        mem_limit: 2G

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "3000:80" # Map port 80 of the container to port 3000 on the host
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf # Custom Nginx configuration
        networks:
            - app-network
        cpus: "2.0" # Limit to 2 CPUs
        mem_limit: 2G

    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        cpus: "2.0" # Limit to 2 CPUs
        mem_limit: 2G

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
